"""Adversarial self-play: ship a proof-of-exploit with every reachable path.

The defense-aware eval publishes what Attestral MISSES honestly; this is the
complement, demonstrating what it CATCHES. A finding like "lethal trifecta" or
the agent->cloud-admin reach is abstract until you see the concrete path, so for
each reachable path this composes three things the rest of the pipeline already
produces: the modeled path (deterministic, from the symbolic walk), an
LLM-narrated exploitation scenario (reused from `redteam.draft_exploit`, gated on
a key and skipped gracefully without one), and a runnable, gated test that
asserts the path exists.

The safeguard is the point. An LLM narrating an exploit can wander off the
modeled path and invent a component or a hop that the design does not contain, so
the scenario is validated STRUCTURALLY against the model before it is trusted:
`check_faithfulness` rejects any scenario that names a surface not on the path it
claims to exploit. That check is deterministic and needs no second model - it is
a stronger guard than an LLM judging an LLM, because it is grounded in the system
model itself. This is a demonstration aid, never an auto-exploit tool: the
emitted test asserts the path is REACHABLE in the model, it does not execute
anything, and it is gated behind an environment variable so it never runs by
accident.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field

from attestral.model import SystemModel
from attestral.paths import AttackPath, all_attack_paths


@dataclass
class Faithfulness:
    """Whether a narrated scenario stays on the path it claims to exploit."""
    on_path: bool
    off_path: list[str] = field(default_factory=list)   # surfaces named but NOT on the path
    covers: list[str] = field(default_factory=list)     # rungs the scenario references
    reason: str = ""


@dataclass
class ProofOfExploit:
    """One reachable path, its narrated scenario, the faithfulness verdict, and
    a gated test that asserts the path exists."""
    kind: str
    path: str                      # the modeled path, described
    scenario: str                  # the narrated exploit, or a skip note
    scenario_available: bool       # False when no key drafted a scenario
    faithful: Faithfulness
    test_source: str


def _path_components(path: AttackPath) -> list[str]:
    seen: list[str] = []
    for stage in (path.entry, path.pivot, path.impact):
        for name in stage.components:
            if name not in seen:
                seen.append(name)
    return seen


def _mentions(text: str, name: str) -> bool:
    return re.search(rf"\b{re.escape(name)}\b", text) is not None


def check_faithfulness(scenario: str, path: AttackPath, model: SystemModel) -> Faithfulness:
    """Validate a narrated scenario against the modeled path. A scenario is
    faithful when every model surface it names is on THIS path (it did not wander
    to a different component) and it actually references the pivot and impact rungs
    (it narrates this path, not a generic story). Deterministic; grounded in the
    model, so a hallucinated hop cannot pass."""
    on_names = set(_path_components(path))
    all_names = {c.name for c in model.tool_surfaces()}
    off_path = sorted(n for n in all_names - on_names if _mentions(scenario, n))

    covers = []
    for role, stage in (("entry", path.entry), ("pivot", path.pivot), ("impact", path.impact)):
        if any(_mentions(scenario, n) for n in stage.components):
            covers.append(role)

    narrates_path = "pivot" in covers and "impact" in covers
    on_path = not off_path and narrates_path
    if off_path:
        reason = f"names off-path surface(s) not on this path: {', '.join(off_path)}"
    elif not narrates_path:
        reason = "does not reference the pivot and impact of the claimed path"
    else:
        reason = "stays on the modeled path"
    return Faithfulness(on_path, off_path, covers, reason)


def emit_proof_test(path: AttackPath, target: str) -> str:
    """A runnable, gated pytest asserting this path is reachable in the model. It
    proves the path EXISTS; it executes nothing. Gated behind ATTESTRAL_PROOF=1 so
    it never runs by accident."""
    slug = re.sub(r"[^a-z0-9]+", "_", path.kind.lower()).strip("_") or "path"
    return (
        f"# Proof-of-exploit: a reachable path in {target}\n"
        "# GENERATED by `attestral validate --proof-of-exploit`. It asserts the\n"
        "# modeled path is REACHABLE; it does not execute anything. A demonstration\n"
        "# aid, not an exploit. Gated: set ATTESTRAL_PROOF=1 to run.\n"
        "import os\n"
        "import pytest\n"
        "from attestral.ingest import build_model\n"
        "from attestral.paths import all_attack_paths\n"
        "\n"
        "pytestmark = pytest.mark.skipif(\n"
        '    os.environ.get("ATTESTRAL_PROOF") != "1",\n'
        '    reason="gated proof-of-exploit; set ATTESTRAL_PROOF=1 to run")\n'
        "\n"
        f"def test_{slug}_path_is_reachable():\n"
        f"    model = build_model({target!r})\n"
        "    reachable = {p.describe() for p in all_attack_paths(model)}\n"
        f"    assert {path.describe()!r} in reachable\n"
    )


def proofs_of_exploit(model: SystemModel, target: str, query=None) -> list[ProofOfExploit]:
    """A proof-of-exploit for every reachable path: the modeled path, a narrated
    scenario (gated on a key, skipped gracefully without one), the faithfulness
    verdict, and a gated test. `query` is an injectable `(prompt) -> str` so tests
    need no key."""
    from attestral.redteam import draft_exploit

    out: list[ProofOfExploit] = []
    for path in all_attack_paths(model):
        draft = draft_exploit(model, path, query=query)
        available = bool(draft.text)
        if available:
            faithful = check_faithfulness(draft.text, path, model)
            scenario = draft.text
        else:
            faithful = Faithfulness(False, [], [], "no scenario drafted (no API key)")
            scenario = draft.note
        out.append(ProofOfExploit(
            kind=path.kind, path=path.describe(), scenario=scenario,
            scenario_available=available, faithful=faithful,
            test_source=emit_proof_test(path, target)))
    return out


def render_proofs_of_exploit(model: SystemModel, target: str, *,
                             color: bool | None = None, query=None,
                             proofs: list[ProofOfExploit] | None = None) -> str:
    """Terminal block: each reachable path, its narrated scenario, the
    faithfulness verdict, and the gated test that ships with it. Pass `proofs` to
    render an already-computed list (so a scenario is not drafted twice)."""
    from attestral.report_terminal import _bold, _dim, _paint, supports_color
    if color is None:
        color = supports_color()
    if proofs is None:
        proofs = proofs_of_exploit(model, target, query=query)
    if not proofs:
        return ""
    lines = [_paint(
        f"Proof-of-exploit ({len(proofs)} reachable path(s) - demonstration, not executed)",
        "1;31", color)]
    for p in proofs:
        lines.append(f"  {_bold(p.kind + ' path', color)}: {p.path}")
        if p.scenario_available:
            verdict = (_paint("faithful to the modeled path", "32", color)
                       if p.faithful.on_path
                       else _paint(f"REJECTED - {p.faithful.reason}", "1;31", color))
            lines.append(f"    {_dim('scenario:', color)} {verdict}")
        else:
            lines.append(f"    {_dim('scenario:', color)} {_dim(p.scenario, color)}")
        lines.append(f"    {_dim('ships a gated test asserting this path is reachable', color)}")
    lines.append(_dim(
        "  the test proves the path exists in the model; it executes nothing and is "
        "gated behind ATTESTRAL_PROOF=1.", color))
    return "\n".join(lines)
